# extractbb-lua
# https://github.com/gucci-on-fleek/extractbb
# SPDX-License-Identifier: MPL-2.0+
# SPDX-FileCopyrightText: 2024--2025 Max Chernoff
when:
  - event: [push, tag, pull_request]
    branch: master

steps:
  - name: Build
    image: maxchernoff.ca/tex-wine:latest
    pull: true
    commands:
      - set -euo pipefail
      - export TEXMFHOME=$(realpath ./texmf)
      - l3build doc &
      - >
        parallel --will-cite l3build check --dirty --show-log-on-error --engine='{}' ::: ebb xbb wine_ebb wine_xbb
      - wait
      - l3build bundle

  - name: Release
    when:
      event: tag
    image: woodpeckerci/plugin-release
    settings:
      title: ./release.title
      files:
        - extractbb-*.tds.zip
        - extractbb-*.ctan.zip
      api_key:
        from_secret: GITHUB_TOKEN
